### PR TITLE
Fix androidTest issue

### LINKED ISSUE #26: Android Basics: Dogglers app - issue on androidTest
**URL of codelab**
[Project: Doggler app](https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2
)

**In which task and step of the codelab can this issue be found?**
While running my test cases

**Describe the problem**
There are four test cases
1. ButtonTests - which has no issue
2. The rest three has one issue on `checkFirstPosition` function

### Actual code:
```kotlin
 fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "7", "sunbathing",
            R.drawable.tzeitel)
    }
```

### But the function should be:
```kotlin
 fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "Age: 7", "Hobbies: sunbathing",
            R.drawable.tzeitel)
    }
```

image

In the colab it has `age` and `hobbies` before the actual content

So I think the `checkFirstPosition` test case is wrong

**Steps to reproduce?**
1. Go to  `androidTest`
2. Run any test case except `ButtonTests` such as `HorizontalListTests` 
3. See error...

image

### PR DESCRIPTION
**Pull request by viktorhrekh**
Fixes #26.
Added "Age" and "Hobbies" prefixes for passing tests by correct implementation.

### CODE REVIEW

**Review by RomanRC99 — APPROVED** [review]

**Comment by lixoten** [comment]
> Fixes #26. Added "Age" and "Hobbies" prefixes for passing tests by correct implementation.

Fix has not been added to the downloadable zip file

**Comment by ashirobokov** [comment]
It seems this fix haven't been merged yet. I don't see these changes at BaseTest.kt (branch `main`).

**Comment by viktorhrekh** [comment]
@OwenLaRosa @osuleymanova @android-dev-lxl @OwenScott-GDS

**Comment by android-dev-lxl** [comment]
@viktorhrekh 
Could you please sign the CLA! We need it to merge your PR.

**Comment by viktorhrekh** [comment]
> @viktorhrekh
> Could you please sign the Contributor License Agreement (CLA)! We need it to merge your PR.
> The CLA only needs to be signed once and it covers all Google projects.
> https://cla.developers.google.com/

Signed!
@android-dev-lxl

**Pull request merged**
